
services:
  postgres: # https://hub.docker.com/_/postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    healthcheck:
      test: 
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      database:
        aliases:
          - postgres
      gateway:
        aliases:
          - postgres
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 1024M
      restart_policy:
        condition: on-failure

networks:
  database:
    name: database
    attachable: true
    enable_ipv6: true
  gateway:
    external: true
    enable_ipv6: true

volumes:
  postgres:
    name: postgres
